### ISSUE TITLE
Would this map_controller keep our custom Marker's internal state?

### ISSUE THREAD

**Issue by aytunch** [synw/map_controller#2]
Specifically when the marker is disposed because it is out of the screen and comes back in again(created)

**Comment by synw** [comment]
Actually not, it just provides a way to manage the map assets. But as this is a recurring problem I started an implementation of stateful markers in a [branch](https://github.com/synw/map_controller/tree/stateful_markers)

It seems to be working, check the [example](https://github.com/synw/map_controller/blob/stateful_markers/example/lib/stateful_markers.dart) and tell me what you think of the api please

**Comment by synw** [comment]
Stateful markers has been released in 0.7.0
