### ISSUE TITLE
Version issues

### ISSUE THREAD

**Issue by joao10martins** [synw/map_controller#20]
C:\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in NextTripMobile...                  

Because map_controller >=0.8.0 depends on rxdart ^0.24.1 and [YOUR_APP_NAME] depends on rxdart ^0.25.0, map_controller >=0.8.0 is forbidden.
So, because [YOUR_APP_NAME] depends on map_controller ^0.8.0, version solving failed.
pub get failed (1; So, because [YOUR_APP_NAME] depends on map_controller ^0.8.0, version solving failed.)

Process finished with exit code 1

**Comment by synw** [comment]
Fixed in 0.9.0

**Comment by icangku** [comment]
rxdart ^0.26.0-nullsafety.1

**Comment by manhlh** [comment]
![image](https://user-images.githubusercontent.com/17887196/128967333-0aa08590-6b1b-42cb-bf90-5be6e823b730.png)
