### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by Pappajo** [synw/map_controller#3]
Please update flutter_map to the newest version.

**Comment by synw** [comment]
I did not upgrade to flutter map 0.8.0 yet because Flutter 1.12 is creating too many problems. I tried and rolled back to 1.9 for now. I will wait a little bit more before making the switch because I need stability for my projects. Please fork or use dependency_overrides for the moment

**Comment by synw** [comment]
I finally made the move: version 0.6.0 is out and supports Flutter 1.12+
