### ISSUE TITLE
How to show geojson file ??

### ISSUE THREAD

**Issue by manhlh** [synw/map_controller#6]
I have get example code, but can't show geojson file.

**Comment by synw** [comment]
What do you mean? The example does not work? Please give more details and stacktrace if you have

**Comment by manhlh** [comment]
![image](https://user-images.githubusercontent.com/17887196/75640905-22007c00-5c69-11ea-9f95-1edff8d48b01.png)
it here, i get string value geojson file, but can't display on map

**Comment by synw** [comment]
Is there an exception or some message displayed in the console? Everything works well here. Try with another device maybe just to see what happens
