### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by andreystavitsky** [synw/map_controller#9]
map_controller >=0.7.0 depends on flutter_map ^0.8.2, current version of flutter_map is 0.9.0

**Comment by X-SLAYER** [comment]
yes i think its need an update

**Comment by xantiagoma** [comment]
Doesn't have either support for version 0.10.

**Comment by Swepilot** [comment]
Also looking for 0.10.x support

**Comment by berkayoruc** [comment]
need update dependencies cupertino icon and flutter_map

**Comment by synw** [comment]
Fixed in 0.9.0
